Payroll/Controllers/BonusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Payroll.Models;

namespace Payroll.Controllers
{
    public class BonusController : Controller
    {
        private readonly PayrollContext _context;

        public BonusController(PayrollContext context)
        {
            _context = context;
        }

        // GET: Bonus
        public async Task<IActionResult> Index()
        {
            var payrollContext = _context.Bonus.Include(b => b.AbsentCase).Include(b => b.BonusDepNavigation);
            return View(await payrollContext.ToListAsync());
        }

        // GET: Bonus/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bonu = await _context.Bonus
                .Include(b => b.AbsentCase)
                .Include(b => b.BonusDepNavigation)
                .FirstOrDefaultAsync(m => m.BonusId == id);
            if (bonu == null)
            {
                return NotFound();
            }

            return View(bonu);
        }

        // GET: Bonus/Create
        public IActionResult Create()
        {
            ViewData["AbsentCaseId"] = new SelectList(_context.LkupAbsents, "AbsentId", "DaysNumber");
            ViewData["BonusDep"] = new SelectList(_context.Departments, "DepId", "DepName");
            return View();
        }

        // POST: Bonus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BonusId,BonusDep,Bouns,Annual,Discount,AbsentCaseId")] Bonu bonu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bonu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AbsentCaseId"] = new SelectList(_context.LkupAbsents, "AbsentId", "DaysNumber", bonu.AbsentCaseId);
            ViewData["BonusDep"] = new SelectList(_context.Departments, "DepId", "DepName", bonu.BonusDep);
            return View(bonu);
        }

        // GET: Bonus/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bonu = await _context.Bonus.FindAsync(id);
            if (bonu == null)
            {
                return NotFound();
            }
            ViewData["AbsentCaseId"] = new SelectList(_context.LkupAbsents, "AbsentId", "DaysNumber", bonu.AbsentCaseId);
            ViewData["BonusDep"] = new SelectList(_context.Departments, "DepId", "DepName", bonu.BonusDep);
            return View(bonu);
        }

        // POST: Bonus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("BonusId,BonusDep,Bouns,Annual,Discount,AbsentCaseId")] Bonu bonu)
        {
            if (id != bonu.BonusId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bonu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BonuExists(bonu.BonusId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AbsentCaseId"] = new SelectList(_context.LkupAbsents, "AbsentId", "DaysNumber", bonu.AbsentCaseId);
            ViewData["BonusDep"] = new SelectList(_context.Departments, "DepId", "DepName", bonu.BonusDep);
            return View(bonu);
        }

        // GET: Bonus/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bonu = await _context.Bonus
                .Include(b => b.AbsentCase)
                .Include(b => b.BonusDepNavigation)
                .FirstOrDefaultAsync(m => m.BonusId == id);
            if (bonu == null)
            {
                return NotFound();
            }

            return View(bonu);
        }

        // POST: Bonus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            var bonu = await _context.Bonus.FindAsync(id);
            _context.Bonus.Remove(bonu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BonuExists(decimal id)
        {
            return _context.Bonus.Any(e => e.BonusId == id);
        }
    }
}

Payroll/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Payroll.Models;

namespace Payroll.Controllers
{
    public class JobsController : Controller
    {
        private readonly PayrollContext _context;

        public JobsController(PayrollContext context)
        {
            _context = context;
        }

        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            var payrollContext = _context.Jobs.Include(j => j.JobDepNavigation);
            return View(await payrollContext.ToListAsync());
        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs
                .Include(j => j.JobDepNavigation)
                .FirstOrDefaultAsync(m => m.JobId == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // GET: Jobs/Create
        public IActionResult Create()
        {
            ViewData["JobDep"] = new SelectList(_context.Departments, "DepId", "DepName");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("JobId,JobName,JobDescription,JobDep,SalaryRange,JobDep")] Job job)
        {
            if (ModelState.IsValid)
            {
                _context.Add(job);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobDep"] = new SelectList(_context.Departments, "DepId", "DepName", job.JobDep);
            return View(job);
        }

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            ViewData["JobDep"] = new SelectList(_context.Departments, "DepId", "DepName", job.JobDep);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("JobId,JobName,JobDescription,JobDep,SalaryRange")] Job job)
        {
            if (id != job.JobId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.JobId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobDep"] = new SelectList(_context.Departments, "DepId", "DepName", job.JobDep);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs
                .Include(j => j.JobDepNavigation)
                .FirstOrDefaultAsync(m => m.JobId == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            var job = await _context.Jobs.FindAsync(id);
            _context.Jobs.Remove(job);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        private bool JobExists(decimal id)
        {
            return _context.Jobs.Any(e => e.JobId == id);
        }
    }
}

Payroll/Controllers/ReportsController.cs
using AspNetCore.Reporting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Payroll.Models;
using Payroll.Report;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Text;
using System.Threading.Tasks;

namespace Payroll.Controllers
{
    public class ReportsController : Controller
    {
        private readonly PayrollContext _context;

        public ReportsController(PayrollContext context)
        {
            _context = context;
        }

        // GET: Attendances
        public IActionResult EmployeeReport()
        {
            var employees = _context.Employees.Include(x=>x.Dep).Include(x=>x.Job);
            List<EmployeeReport> employeeReport = new();
            foreach (var em in employees)
            {
                employeeReport.Add(new EmployeeReport()
                {
                    EMP_NAME = em.EmpName,
                    EMP_ADDRESS = em.EmpAddress,
                    EMP_EMAIL = em.EmpEmail,
                    EMP_PHONE = em.EmpPhone,
                    DEP_ID = em.Dep?.DepName,
                    JOB_ID = em.Job?.JobName,
                    HIRE_DATE = em.HireDate
                });
            }
            var reportFileByteString = GenerateReportAsync("DataSet1",employeeReport,"EmployeeReport");
            return File(reportFileByteString, MediaTypeNames.Application.Octet, getReportName("EmployeeReport", "pdf"));
        }
        public IActionResult AttendanceReport()
        {
            var attendances = _context.Attendances.Include(a => a.Emp).Include(x=>x.AbsentCase);
            List<Payroll.Report.AttendancesReport> attendancesReport = new();
            foreach (var attend in attendances)
            {
                attendancesReport.Add(new Payroll.Report.AttendancesReport()
                {
                    EMP_ID = attend.Emp?.EmpName,
                    ABSENT_CASE_ID = attend.AbsentCase?.DaysNumber,
                    ABSENT_DATE = attend.AbsentDate,
                    ABSENT_REASON = attend.AbsentReason,
                    ATTEND_DATE = attend.AttendDate,
                    LEAVE_DATE = attend.LeaveDate
                });
            }
            var reportFileByteString = GenerateReportAsync("DataSet2",attendancesReport, "AttendancesReport");
            return File(reportFileByteString, MediaTypeNames.Application.Octet, getReportName("AttendancesReport", "pdf"));
        }
        public IActionResult SalaryBonusDiscountReport()
        {
            var payrolls = _context.PayrollReports
                .Include(x => x.Emp)
                .Include(x => x.Job)
                .Include(x => x.Salary)
                .Include(x=>x.Attendance).ThenInclude(x=>x.AbsentCase);
            List<Payroll.Report.SalaryBonusDiscountReport> employeeReport = new();
            if(payrolls.Any())
            {
                foreach (var payroll in payrolls)
                {
                    employeeReport.Add(new Payroll.Report.SalaryBonusDiscountReport()
                    {
                        EMP_ID = payroll.Emp?.EmpName,
                        ATTENDANCE_ID = payroll.Attendance?.AbsentCase?.DaysNumber,
                        PAYROLL_DATE = payroll.PayrollDate,
                        Job_ID = payroll.Job?.JobName,
                        SALARY_ID = payroll.Salary?.Amount ?? 0,
                        TOTAL_AMOUNT = payroll.TotalAmount ?? 0,

                    });
                }
            }
           
            var reportFileByteString = GenerateReportAsync("DataSet3", employeeReport, "SalaryBonusDiscountReport");
            return File(reportFileByteString, MediaTypeNames.Application.Octet, getReportName("SalaryBonusDiscountReport", "pdf"));
        }
        private string getReportName(string reportName, string reportType)
        {
            var outputFileName = reportName + ".pdf";

            switch (reportType.ToUpper())
            {
                default:
                case "PDF":
                    outputFileName = reportName + ".pdf";
                    break;
                case "XLS":
                    outputFileName = reportName + ".xls";
                    break;
                case "WORD":
                    outputFileName = reportName + ".doc";
                    break;
            }

            return outputFileName;
        }
        public byte[] GenerateReportAsync(string dataSet,object dataSource,string url)
        {

            string test = $"C:\\Users\\Lenovo\\source\\repos\\Payroll\\Payroll\\Report\\{url}.rdlc";
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Encoding.GetEncoding("utf-8");
            LocalReport report = new LocalReport(test);
           
            report.AddDataSource(dataSet, dataSource);
            Dictionary<string, string> parameters = new Dictionary<string, string>();
            var result = report.Execute(RenderType.Pdf, 1, parameters);

            return result.MainStream;
        }


    }
}

Payroll/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Payroll</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script type="text/javascript">

        function changeFunc() {
            var selectBox = document.getElementById("selectBox");
            var selectedValue = selectBox.options[selectBox.selectedIndex].value;
            

    </script>
    <style>
        nav menuitem {
            position: relative;
            display: block;
            opacity: 0;
            cursor: pointer;
        }

            nav menuitem > menu {
                position: absolute;
                pointer-events: none;
            }

        nav > menu {
            display: flex;
        }

            nav > menu > menuitem {
                pointer-events: all;
                opacity: 1;
            }

        menu menuitem a {
            white-space: nowrap;
            display: block;
        }

        menuitem:hover > menu {
            pointer-events: initial;
        }

            menuitem:hover > menu > menuitem,
            menu:hover > menuitem {
                opacity: 1;
            }

        nav > menu > menuitem menuitem menu {
            transform: translateX(100%);
            top: 0;
            right: 0;
        }
        /* User Styles Below Not Required */
        /* User Styles Below Not Required */
        /* User Styles Below Not Required */

        nav {
            margin-top: 40px;
            margin-left: 40px;
        }

            nav a {
                background: #75F;
                color: white;
                min-width: 190px;
                transition: background 0.5s, color 0.5s, transform 5s;
                margin: 0px 2px 2px 0px;
                padding: 20px 40px;
                box-sizing: border-box;
                border-radius: 3px;
                box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.5);
                position: relative;
            }

                nav a:hover:before {
                    content: '';
                    top: 0;
                    left: 0;
                    position: absolute;
                    background: rgba(0, 0, 0, 0.2);
                    width: 100%;
                    height: 100%;
                }

            nav > menu > menuitem > a + menu:after {
                content: '';
                position: absolute;
                border: 10px solid transparent;
                border-top: 10px solid white;
                left: 12px;
                top: -40px;
            }

            nav menuitem > menu > menuitem > a + menu:after {
                content: '';
                position: absolute;
                border: 10px solid transparent;
                border-left: 10px solid white;
                top: 20px;
                left: -180px;
                transition: opacity 0.6s, transform 0s;
            }

            nav > menu > menuitem > menu > menuitem {
                transition: transform 0.6s, opacity 0.6s;
                transform: translateY(150%);
                opacity: 0;
            }

            nav > menu > menuitem:hover > menu > menuitem,
            nav > menu > menuitem.hover > menu > menuitem {
                transform: translateY(0%);
                opacity: 1;
            }

        menuitem > menu > menuitem > menu > menuitem {
            transition: transform 0.6s, opacity 0.6s;
            transform: translateX(195px) translateY(0%);
            opacity: 0;
        }

        menuitem > menu > menuitem:hover > menu > menuitem,
        menuitem > menu > menuitem.hover > menu > menuitem {
            transform: translateX(0) translateY(0%);
            opacity: 1;
        }
    </style>
</head>
<body>
    <header>
        <nav>
            <menu>
                <menuitem id="reports Department">
                    <a>ادارة التقارير</a>
                    <menu>
                        <menuitem><a asp-controller="Reports" asp-action="EmployeeReport">تقرير بالعاملين بالشركة</a></menuitem>
                        <menuitem><a asp-controller="Reports" asp-action="SalaryBonusDiscountReport">تقرير مرتبات العاملين بالحوافز والخصومات</a></menuitem>
                        <menuitem><a asp-controller="Reports" asp-action="AttendanceReport">تقرير بالحضور والانصراف</a></menuitem>

                    </menu>
                </menuitem>
                <menuitem id="bonus Department">
                    <a>ادارة الحوافز والخصومات</a>
                    <menu>
                        <menuitem><a asp-controller="Bonus" asp-action="Index">عرض جميع الحوافز والخصومات</a></menuitem>
                        <menuitem><a asp-controller="Bonus" asp-action="Create">اضافة حافز او خصم</a></menuitem>
                    </menu>
                </menuitem>
                <menuitem id="salary Department">
                    <a>ادارة المرتبات</a>
                    <menu>
                        <menuitem><a asp-controller="Salaries" asp-action="Index">عرض جميع المرتبات</a></menuitem>
                        <menuitem><a asp-controller="Salaries" asp-action="Create">اضافة مرتب</a></menuitem>
                        <menuitem><a asp-controller="PayrollReports" asp-action="Index">جميع الرواتب المصروفة</a></menuitem>
                        <menuitem><a asp-controller="PayrollReports" asp-action="Create">صرف مرتبات الموظفين</a></menuitem>
                        
                    </menu>
                </menuitem>
                <menuitem id="Job Department">
                    <a>ادارة الحضور والانصارف</a>
                    <menu>
                        <menuitem><a asp-controller="Attendances" asp-action="Index">عرض كشف الحضور</a></menuitem>
                        <menuitem><a asp-controller="Attendances" asp-action="Create">تسجيل حضور وانصارف وغياب</a></menuitem>
                    </menu>
                </menuitem>
                <menuitem id="employee">
                    <a>ادارة الموظفين</a>
                    <menu>
                        <menuitem><a asp-controller="Employees" asp-action="Index">عرض جميع الموظفين</a></menuitem>
                        <menuitem><a asp-controller="Employees" asp-action="Create">اضافة موظف</a></menuitem>
                    </menu>
                </menuitem>
                <menuitem id="Job Department">
                    <a>ادارة الوظائف</a>
                    <menu>
                        <menuitem><a asp-controller="Jobs" asp-action="Index">عرض جميع الدرجات الوظيفية</a></menuitem>
                        <menuitem><a asp-controller="Jobs" asp-action="Create">اضافة درجة وظيفية</a></menuitem>
                    </menu>
                </menuitem>
                <menuitem id="Job Department">
                    <a>ادارة الاقسام</a>
                    <menu>
                        <menuitem><a asp-controller="Departments" asp-action="Index">عرض جميع الاقسام</a></menuitem>
                        <menuitem><a asp-controller="Departments" asp-action="Create">اضافة قسم جديد</a></menuitem>
                    </menu>
                </menuitem>

            </menu>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Payroll - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>