Payroll/Models/PayrollReport.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Payroll.Models
{
    public partial class PayrollReport
    {
        public decimal PayrollId { get; set; }
        public decimal? EmpId { get; set; }
        public decimal? JobId { get; set; }
        public decimal? SalaryId { get; set; }
        public decimal? AttendanceId { get; set; }
        public DateTime? PayrollDate { get; set; }
        public decimal? TotalAmount { get; set; }

        public virtual Attendance Attendance { get; set; }
        public virtual Employee Emp { get; set; }
        public virtual Job Job { get; set; }
        public virtual Salary Salary { get; set; }
    }
}

Payroll/Controllers/PayrollReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Payroll.Models;

namespace Payroll.Controllers
{
    public class PayrollReportsController : Controller
    {
        private readonly PayrollContext _context;

        public PayrollReportsController(PayrollContext context)
        {
            _context = context;
        }

        // GET: PayrollReports
        public async Task<IActionResult> Index()
        {
            var payrollContext = _context.PayrollReports
                .Include(p => p.Attendance)
                .ThenInclude(x=>x.AbsentCase)
                .Include(p => p.Emp).Include(p => p.Job).Include(p => p.Salary);
            return View(await payrollContext.ToListAsync());
        }

        // GET: PayrollReports/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payrollReport = await _context.PayrollReports
                .Include(p => p.Attendance)
                .Include(p => p.Emp)
                .Include(p => p.Job)
                .Include(p => p.Salary)
                .FirstOrDefaultAsync(m => m.PayrollId == id);
            if (payrollReport == null)
            {
                return NotFound();
            }

            return View(payrollReport);
        }

        // GET: PayrollReports/Create
        public IActionResult Create(decimal? id )
        {
            if(id == null)
            {
                var emps = _context.Employees.ToList();
                emps.Add(new Employee { EmpId = -1, EmpName = "--Select--" });
                ViewData["AttendanceId"] = new SelectList(_context.Attendances.Include(x => x.AbsentCase), "AttendanceId", "AbsentCase.DaysNumber");
                ViewData["EmpId"] = new SelectList(emps, "EmpId", "EmpName",-1);
                ViewData["JobId"] = new SelectList(_context.Jobs, "JobId", "JobName");
                ViewData["SalaryId"] = new SelectList(_context.Salaries, "SalaryId", "Amount");
            }
            else
            {
                var loadEmployee = _context.Employees.Where(p =>p.EmpId == id)
                    .Include(x=>x.Attendances).ThenInclude(x=>x.AbsentCase)
                    .Include(x => x.Job).ThenInclude(x => x.Salaries)
                    .FirstOrDefault();
                ViewData["AttendanceId"] = new SelectList(loadEmployee.Attendances, "AttendanceId", "AbsentCase.DaysNumber");
                ViewData["EmpId"] = new SelectList(_context.Employees, "EmpId", "EmpName", loadEmployee.EmpId);
                ViewData["JobId"] = new SelectList(_context.Jobs, "JobId", "JobName", loadEmployee.Job.JobId);
                ViewData["SalaryId"] = new SelectList(_context.Salaries, "SalaryId", "Amount", loadEmployee.Job.Salaries.FirstOrDefault().SalaryId);
               
            }
            
            return View();
        }

        // POST: PayrollReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PayrollId,EmpId,JobId,SalaryId,AttendanceId,PayrollDate,TotalAmount")] PayrollReport payrollReport)
        {
            if (ModelState.IsValid)
            {
                payrollReport.TotalAmount = CalculateTotalAmount(payrollReport);
                _context.Add(payrollReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AttendanceId"] = new SelectList(_context.Attendances.Include(x => x.AbsentCase), "AttendanceId", "AbsentCase.DaysNumber", payrollReport.AttendanceId);
            ViewData["EmpId"] = new SelectList(_context.Employees, "EmpId", "EmpName", payrollReport.EmpId);
            ViewData["JobId"] = new SelectList(_context.Jobs, "JobId", "JobName", payrollReport.JobId);
            ViewData["SalaryId"] = new SelectList(_context.Salaries, "SalaryId", "Amount", payrollReport.SalaryId);
            return View(payrollReport);
        }

        // GET: PayrollReports/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payrollReport = await _context.PayrollReports.FindAsync(id);
            if (payrollReport == null)
            {
                return NotFound();
            }
            ViewData["AttendanceId"] = new SelectList(_context.Attendances, "AttendanceId", "AttendanceId", payrollReport.AttendanceId);
            ViewData["EmpId"] = new SelectList(_context.Employees, "EmpId", "EmpName", payrollReport.EmpId);
            ViewData["JobId"] = new SelectList(_context.Jobs, "JobId", "JobName", payrollReport.JobId);
            ViewData["SalaryId"] = new SelectList(_context.Salaries, "SalaryId", "Amount", payrollReport.SalaryId);
            return View(payrollReport);
        }

        // POST: PayrollReports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("PayrollId,EmpId,JobId,SalaryId,AttendanceId,PayrollDate,TotalAmount")] PayrollReport payrollReport)
        {
            if (id != payrollReport.PayrollId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payrollReport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PayrollReportExists(payrollReport.PayrollId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AttendanceId"] = new SelectList(_context.Attendances, "AttendanceId", "AttendanceId", payrollReport.AttendanceId);
            ViewData["EmpId"] = new SelectList(_context.Employees, "EmpId", "EmpName", payrollReport.EmpId);
            ViewData["JobId"] = new SelectList(_context.Jobs, "JobId", "JobName", payrollReport.JobId);
            ViewData["SalaryId"] = new SelectList(_context.Salaries, "SalaryId", "Amount", payrollReport.SalaryId);
            return View(payrollReport);
        }

        // GET: PayrollReports/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payrollReport = await _context.PayrollReports
                .Include(p => p.Attendance)
                .Include(p => p.Emp)
                .Include(p => p.Job)
                .Include(p => p.Salary)
                .FirstOrDefaultAsync(m => m.PayrollId == id);
            if (payrollReport == null)
            {
                return NotFound();
            }

            return View(payrollReport);
        }

        // POST: PayrollReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            var payrollReport = await _context.PayrollReports.FindAsync(id);
            _context.PayrollReports.Remove(payrollReport);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        private bool PayrollReportExists(decimal id)
        {
            return _context.PayrollReports.Any(e => e.PayrollId == id);
        }
        private decimal CalculateTotalAmount(PayrollReport payrollReport)
        {
            decimal totalAmount = 0;
            //init with gross salary
            var gross = _context.Salaries.FirstOrDefault(x=>x.SalaryId == payrollReport.SalaryId)?.Amount ?? 0;
            //emp attendances
            var attendance = _context.Attendances.FirstOrDefault(x=>x.AttendanceId == payrollReport.AttendanceId);
            //department details with bonus/discount
            var Dep_job = _context.Jobs.Where(x => x.JobId == payrollReport.JobId)
                                    .FirstOrDefault();
            //bonus 
            
            var bonusPercentage = _context.Bonus.FirstOrDefault(x =>x.BonusDep == Dep_job.JobDep && x.AbsentCaseId == attendance.AbsentCaseId)?
                                    .Bouns??0;
            //annual bonus
            var annualBonusPercentage = _context.Bonus.FirstOrDefault(x => x.BonusDep == Dep_job.JobDep && x.AbsentCaseId == attendance.AbsentCaseId)?
                                    .Annual ?? 0;
            var hireTime = _context.Employees.FirstOrDefault(x => x.EmpId == payrollReport.EmpId).HireDate ?? DateTime.Now;
            TimeSpan span = DateTime.Now - hireTime;
            DateTime zeroTime = new DateTime(1, 1, 1);
            var numberOfYers = (zeroTime + span).Year - 1;
            //discount
            var discountPercentage = _context.Bonus.FirstOrDefault(x => x.BonusDep == Dep_job.JobDep && x.AbsentCaseId == attendance.AbsentCaseId)?
                                    .Discount??0;
            //add the gross

Payroll/Views/PayrollReports/Create.cshtml
@model Payroll.Models.PayrollReport

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}
<script type="text/javascript">
    function GetSelectedTextValue() {
        var selected = document.getElementById("EmpId");
        var selectedValueEmpId = selected.value;
        var link = '@Url.Action("Create", "PayrollReports", new { id = "-1" })';
        link = link.replace("-1", selectedValueEmpId);

        window.location.href = link;

    }
</script>
<h1>Create</h1>

<h4>PayrollReport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmpId" class="control-label"></label>
                <select asp-for="EmpId" class="form-control" asp-items="ViewBag.EmpId" onchange="GetSelectedTextValue()"></select>
            </div>
            <div class="form-group">
                <label asp-for="AttendanceId" class="control-label"></label>
                <select asp-for="AttendanceId" class="form-control" asp-items="ViewBag.AttendanceId"></select>
            </div>
            <div class="form-group">
                <label asp-for="PayrollDate" class="control-label"></label>
                <input asp-for="PayrollDate" class="form-control" />
                <span asp-validation-for="PayrollDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <select disabled asp-for="JobId" class="form-control" asp-items="ViewBag.JobId"></select>
            </div>
            <div class="form-group">
                <select hidden asp-for="JobId" class="form-control" asp-items="ViewBag.JobId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SalaryId" class="control-label"></label>
                <select disabled asp-for="SalaryId" class="form-control" asp-items="ViewBag.SalaryId"></select>
            </div>
            <div class="form-group">
                <select hidden asp-for="SalaryId" class="form-control" asp-items="ViewBag.SalaryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input readonly asp-for="TotalAmount" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Payroll/Views/PayrollReports/Delete.cshtml
@model Payroll.Models.PayrollReport

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PayrollReport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayrollDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayrollDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Attendance)
        </dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emp.EmpId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Job)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Job.JobName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary.Amount)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PayrollId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Payroll/Views/PayrollReports/Details.cshtml
@model Payroll.Models.PayrollReport

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>PayrollReport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayrollDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayrollDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emp.EmpId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Job)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Job.JobId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary.SalaryId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PayrollId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Payroll/Views/PayrollReports/Edit.cshtml
@model Payroll.Models.PayrollReport

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>PayrollReport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PayrollId" />
            <div class="form-group">
                <label asp-for="EmpId" class="control-label"></label>
                <select asp-for="EmpId" class="form-control" asp-items="ViewBag.EmpId"></select>
                <span asp-validation-for="EmpId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <select asp-for="JobId" class="form-control" asp-items="ViewBag.JobId"></select>
                <span asp-validation-for="JobId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalaryId" class="control-label"></label>
                <select asp-for="SalaryId" class="form-control" asp-items="ViewBag.SalaryId"></select>
                <span asp-validation-for="SalaryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AttendanceId" class="control-label"></label>
                <select asp-for="AttendanceId" class="form-control" asp-items="ViewBag.AttendanceId"></select>
                <span asp-validation-for="AttendanceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayrollDate" class="control-label"></label>
                <input asp-for="PayrollDate" class="form-control" />
                <span asp-validation-for="PayrollDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input readonly asp-for="TotalAmount" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Payroll/Views/PayrollReports/Index.cshtml
@model IEnumerable<Payroll.Models.PayrollReport>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Emp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Job)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PayrollDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmount)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Attendance.AbsentCase.DaysNumber)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Emp.EmpName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Job.JobName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayrollDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalAmount)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Attendance.AbsentCase.DaysNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PayrollId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PayrollId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PayrollId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>